name: test-workflow
version: 1.0.0
specVersion: "1.0"
description: >
  A simple test workflow that demonstrates basic Agentfile functionality
  with a hello world example.

execution:
  preferred: "ide"

trigger:
  type: natural-language
  input_var: USER_REQUEST

output:
  directory: outputs

steps:
  - id: greet
    name: Hello World Greeting
    agent: agents/greeter.md
    skill: skills/hello-world.md
    input: $USER_REQUEST
    goal: Generate a friendly hello world greeting
    produces: outputs/greeting.md

  - id: process
    name: Process Request
    agent: agents/processor.md
    skill: skills/process-request.md
    input: 
      - outputs/greeting.md
      - $USER_REQUEST
    goal: Process the user's request and provide a response
    produces: outputs/response.md
