name: code-reviewer
version: 1.0.0
specVersion: "1.0"
description: >
  An automated code review pipeline that systematically inspects, analyzes, and evaluates source code changes before merging to main branch or deployment. The workflow maintains code quality, ensures consistency, and catches issues early in the development lifecycle through multi-faceted analysis including static analysis, security scanning, style checking, and complexity assessment. On successful completion, outputs can be passed to the git-commit workflow for automated commit processing.

execution:
  preferred: "ide"

trigger:
  type: command
  input_var: INPUT_PATH

output:
  directory: outputs/

steps:
  - id: init
    name: Initialize Review Context
    agent: agents/coordinator.md
    skill: skills/setup-review-context.md
    input: $INPUT_PATH
    goal: >
      Load review configuration, identify target code files, set up analysis environment,
      and initialize git context for the code review process.
    produces: outputs/01-context.md

  - id: static
    name: Static Code Analysis
    agent: agents/static-analyzer.md
    skill: skills/code-quality-analysis.md
    input: outputs/01-context.md
    goal: >
      Perform comprehensive static code analysis including quality metrics, pattern detection,
      and maintainability assessment of the target source code.
    produces: outputs/02-static-analysis.md

  - id: security
    name: Security Vulnerability Scan
    agent: agents/security-scanner.md
    skill: skills/vulnerability-detection.md
    input: outputs/01-context.md
    goal: >
      Scan source code for security vulnerabilities, anti-patterns, and compliance issues
      using security analysis tools and vulnerability databases.
    produces: outputs/03-security-scan.md

  - id: style
    name: Style & Standards Check
    agent: agents/style-checker.md
    skill: skills/coding-standards-validation.md
    input: outputs/01-context.md
    goal: >
      Validate source code compliance with coding standards, style guides, and formatting
      rules to ensure consistency across the codebase.
    produces: outputs/04-style-check.md

  - id: complexity
    name: Complexity Analysis
    agent: agents/static-analyzer.md
    skill: skills/complexity-metrics.md
    input: outputs/01-context.md
    goal: >
      Calculate code complexity metrics including cyclomatic complexity, cognitive complexity,
      and maintainability indices to assess code quality.
    produces: outputs/05-complexity-analysis.md

  - id: report
    name: Generate Review Report
    agent: agents/reporter.md
    skill: skills/report-compilation.md
    input: |
      outputs/02-static-analysis.md
      outputs/03-security-scan.md
      outputs/04-style-check.md
      outputs/05-complexity-analysis.md
    goal: >
      Compile all analysis results into a comprehensive review report with categorized findings,
      severity ratings, and actionable recommendations.
    produces: outputs/06-review-report.md

  - id: evaluate
    name: Evaluate Results
    agent: agents/coordinator.md
    skill: skills/result-evaluation.md
    input: |
      outputs/01-context.md
      outputs/06-review-report.md
    goal: >
      Apply configurable pass/fail criteria to the review results and make final approval
      or rejection determination based on quality thresholds.
    produces: outputs/07-evaluation.md

  - id: publish
    name: Publish Findings
    agent: agents/reporter.md
    skill: skills/output-formatting.md
    input: |
      outputs/06-review-report.md
      outputs/07-evaluation.md
    goal: >
      Format and publish the final review output in multiple formats including Markdown,
      JSON for automation, and annotations for pull request comments.
    produces: outputs/08-final-report.md
