name: slash-demo
version: 1.0.0
specVersion: "1.0"
description: >
  A simple demonstration workflow for testing the /agentfile: slash commands.
  Takes a topic and creates a brief summary with key points.

trigger:
  type: natural-language
  input_var: AGENT_INPUT

steps:
  - id: summarize
    name: Create Summary
    agent: agents/summarizer.md
    skill: skills/summarize.md
    input: $AGENT_INPUT
    goal: >
      Create a concise summary of the given topic with 3-5 key points.
      Keep it under 150 words and format with clear bullet points.
    produces: outputs/summary.md
