name: workflow-creator
version: 1.2.0
specVersion: "1.0"
description: >
  A meta-workflow that generates complete workflow packages from natural language
  requests. Outputs are staged in artifacts/<workflow-name>/<run-id>/ (factory)
  before being promoted to workflows/<workflow-name>/ (shipped). Factory files
  never appear in the final workflow. Supports resume via /agentfile:continue.

execution:
  preferred: "ide"

trigger:
  type: command
  commands:
    create:   "/agentfile:create <workflow-name> \"<description>\""
    continue: "/agentfile:continue [workflow-name]"
  input_var: WORKFLOW_REQUEST

# ── Path model ──────────────────────────────────────────────────────────────────
# FACTORY  — artifacts/<workflow-name>/<run-id>/
#   Staging area. Numbered files, _all.md bundles, manifest.json, design docs.
#   Exists only during creation. Archived to outputs/ after promotion.
#   Never referenced by the running workflow.
#
# SHIPPED  — workflows/<workflow-name>/
#   Clean final workflow. Only deliverables: workflow.yaml, agents/, skills/,
#   scripts/utils|cli|ide/, outputs/ (empty, gitignored), workflow_status.json.
#   No factory files. Self-contained. This is what users and scripts reference.
#
# Layout during creation:
#   artifacts/<workflow-name>/<run-id>/
#     manifest.json            <- control plane, updated at every step
#     01-clarification.md
#     02-design.md
#     03-workflow.yaml
#     04-agents/
#     05-skills/
#     06-scripts/
#       ide/
#       cli/
#     07-review.md

output:
  directory: workflows/{workflow_name}

steps:
  - id: init
    name: Initialize Artifact Run
    agent: agents/analyst.md
    skill: skills/generate-manifest.md
    input: $WORKFLOW_REQUEST
    goal: >
      Create the artifact run directory at artifacts/{workflow_name}/{run_id}/
      and write the initial manifest.json with status "generating" and all
      steps set to "pending". The run_id is the current UTC timestamp in the
      format YYYY-MM-DDTHH-MM-SS. Output the run directory path so subsequent
      steps can reference it.
    produces: artifacts/{workflow_name}/{run_id}/manifest.json

  - id: clarify
    name: Clarify Request
    agent: agents/analyst.md
    skill: skills/ask-clarifying.md
    input: $WORKFLOW_REQUEST
    goal: >
      Extract and clarify the workflow's purpose, inputs, outputs, steps,
      agents needed, edge cases, and any ambiguities. Ask the user questions
      if anything is unclear. Update manifest.json: set clarify step to
      in_progress, then completed on finish.
    produces: artifacts/{workflow_name}/{run_id}/01-clarification.md
    gate: human-approval

  - id: design
    name: Design Workflow
    agent: agents/architect.md
    skill: skills/design-workflow.md
    input: artifacts/{workflow_name}/{run_id}/01-clarification.md
    goal: >
      Design the complete workflow structure: step list, agent roles,
      skills needed, ALL required scripts (CLI and IDE with equal depth —
      plus any additional scripts like setup, watch, batch, or hook installers),
      inter-workflow connections (upstream/downstream triggers), and file manifest.
      Update manifest.json step status on start and completion.
    produces: artifacts/{workflow_name}/{run_id}/02-design.md
    gate: human-approval

  - id: generate-config
    name: Generate workflow.yaml
    agent: agents/generator.md
    skill: skills/generate-yaml.md
    input: artifacts/{workflow_name}/{run_id}/02-design.md
    goal: >
      Generate the workflow.yaml config file for the new workflow.
      Register the file in manifest.json files[] with role "workflow_config".
    produces: artifacts/{workflow_name}/{run_id}/03-workflow.yaml

  - id: generate-agents
    name: Generate Agent Files
    agent: agents/generator.md
    skill: skills/generate-agent.md
    input: artifacts/{workflow_name}/{run_id}/02-design.md
    goal: >
      Generate all agent .md files defined in the design.
      Write them to artifacts/{workflow_name}/{run_id}/04-agents/.
      Register each file in manifest.json with role "agent".
    produces: artifacts/{workflow_name}/{run_id}/04-agents/

  - id: generate-skills
    name: Generate Skill Files
    agent: agents/generator.md
    skill: skills/generate-skill.md
    input: artifacts/{workflow_name}/{run_id}/02-design.md
    goal: >
      Generate all skill .md files defined in the design.
      Write them to artifacts/{workflow_name}/{run_id}/05-skills/.
      Register each file in manifest.json with role "skill".
    produces: artifacts/{workflow_name}/{run_id}/05-skills/

  - id: generate-utils
    name: Generate Utility Scripts
    agent: agents/generator.md
    skill: skills/generate-utils.md
    input: artifacts/{workflow_name}/{run_id}/02-design.md
    goal: >
      Analyse the workflow design and identify every non-LLM operation — file reads,
      writes, validation, transformation, environment checks, etc. Generate a dedicated
      utility script (both .sh and .ps1) for each operation. Write to
      artifacts/{workflow_name}/{run_id}/06-scripts/utils/. These will be called by
      both cli/ and ide/ scripts. Register each with role "script_utils" in manifest.json.
    produces: artifacts/{workflow_name}/{run_id}/06-scripts/utils/

  - id: generate-scripts
    name: Generate CLI and IDE Scripts
    agent: agents/generator.md
    skill: skills/generate-dual-scripts.md
    input:
      - artifacts/{workflow_name}/{run_id}/02-design.md
      - artifacts/{workflow_name}/{run_id}/06-scripts/utils/
    goal: >
      Generate BOTH CLI and IDE execution scripts with equal completeness. CLI scripts
      (run.sh, run.ps1) MUST implement execution-state — init_state(), check_gate(),
      step_start(), step_complete(), step_fail(), step_await_approval(), and --resume
      support via locate_run(). Gated steps must call step_await_approval and exit 0.
      Both must call into utils/ scripts for non-LLM work. IDE scripts (instructions.md,
      steps.md, register.sh, register.ps1) reference utils/ where needed. Write to
      artifacts/{workflow_name}/{run_id}/06-scripts/cli/ and 06-scripts/ide/.
      Register each file with the appropriate role in manifest.json.
    produces: artifacts/{workflow_name}/{run_id}/06-scripts/

  - id: review
    name: Review All Outputs
    agent: agents/reviewer.md
    skill: skills/review-workflow.md
    input:
      - artifacts/{workflow_name}/{run_id}/02-design.md
      - artifacts/{workflow_name}/{run_id}/03-workflow.yaml
      - artifacts/{workflow_name}/{run_id}/04-agents/
      - artifacts/{workflow_name}/{run_id}/05-skills/
      - artifacts/{workflow_name}/{run_id}/06-scripts/
    goal: >
      Review all generated files for consistency, completeness, and correctness.
      Produce a review report. Flag any issues. Update manifest.json:
      set phases.generation.status to "completed" and phases.validation.status
      to "completed" if review passes. Set status to "validated".
    produces: artifacts/{workflow_name}/{run_id}/07-review.md
    gate: human-approval

  - id: promote
    name: Promote to Workflow
    agent: agents/generator.md
    skill: skills/promote-workflow.md
    input:
      - artifacts/{workflow_name}/{run_id}/manifest.json
      - artifacts/{workflow_name}/{run_id}/03-workflow.yaml
      - artifacts/{workflow_name}/{run_id}/04-agents/
      - artifacts/{workflow_name}/{run_id}/05-skills/
      - artifacts/{workflow_name}/{run_id}/06-scripts/
      - artifacts/{workflow_name}/{run_id}/07-review.md
    goal: >
      Cross the factory→shipped boundary. Assemble ONLY final deliverables into
      workflows/{workflow_name}/ — no manifest.json, no numbered prefixes, no
      _all.md bundles, no design docs. Archive the artifact run to
      outputs/{workflow_name}/{run_id}/build/. Update manifest.json in the archive
      to status "registered". Write workflow_status.json (provenance pointer only)
      to the registered workflow directory. Verify no factory files leaked.
    produces: workflows/{workflow_name}/
