name: file-flow
version: 1.0.0
specVersion: "1.0"

description: >
  A foundational file-processing utility workflow that reads structured data
  from files (JSON/YAML/CSV), parses and transforms their contents, and saves
  validated results in an organized output structure. It is designed as a
  reliable, repeatable file-handling capability used by other workflows
  within automated pipelines.

trigger:
  type: command
  input_var: FILE_FLOW_INPUT

output:
  directory: workflows/file-flow

execution:
  preferred: ide

steps:
  - id: load-instruction
    name: Load Instruction
    agent: agents/instruction-loader.md
    skill: skills/parse-instruction.md
    input: $FILE_FLOW_INPUT
    goal: >
      Read and parse the instruction configuration file to extract file list,
      processing rules, and output configuration.
    produces: artifacts/file-flow/instruction-config.json

  - id: guard-execution
    name: Guard Execution
    agent: agents/execution-guard.md
    skill: skills/workflow-control.md
    input: artifacts/file-flow/instruction-config.json
    goal: >
      Validate required fields exist, prevent partial configs, establish
      workflow state to ensure safe execution.
    produces: artifacts/file-flow/execution-readiness.json

  - id: validate-inputs
    name: Validate Inputs
    agent: agents/file-validator.md
    skill: skills/file-io.md
    input: artifacts/file-flow/instruction-config.json
    goal: >
      Verify that all input files specified in the instruction exist and
      are accessible.
    produces: artifacts/file-flow/input-validation.json

  - id: parse-files
    name: Parse Files
    agent: agents/file-parser.md
    skill: skills/file-parsing.md
    input: artifacts/file-flow/input-validation.json
    goal: >
      Read and parse each input file based on its format (JSON/YAML/CSV)
      into structured data.
    produces: artifacts/file-flow/parsed-data.json

  - id: transform-data
    name: Transform Data
    agent: agents/data-transformer.md
    skill: skills/data-transformation.md
    input: artifacts/file-flow/parsed-data.json
    goal: >
      Apply rule-based restructuring, filtering, or normalization as
      defined in the instruction configuration.
    produces: artifacts/file-flow/transformed-data.json

  - id: validate-output
    name: Validate Output
    agent: agents/output-validator.md
    skill: skills/data-validation.md
    input: artifacts/file-flow/transformed-data.json
    goal: >
      Validate processed data meets schema and validation rules defined
      in the instruction.
    produces: artifacts/file-flow/output-validation.json

  - id: save-results
    name: Save Results
    agent: agents/result-writer.md
    skill: skills/file-io.md
    input: artifacts/file-flow/output-validation.json
    goal: >
      Save processed output to the specified destination directory.
      Only executes if validation succeeded.
    produces: artifacts/file-flow/output-files/

  - id: report-status
    name: Report Status
    agent: agents/status-reporter.md
    skill: skills/execution-logging.md
    input: artifacts/file-flow/
    goal: >
      Generate execution summary with success/failure details for all steps.
    produces: artifacts/file-flow/execution-report.json
