name: pr-summarizer
version: 1.0.0
specVersion: "1.0"
description: >
  Reads a pull request diff and produces a concise, structured summary
  of what changed, why it matters, and what reviewers should focus on.

trigger:
  type: natural-language
  input_var: AGENT_INPUT

steps:
  - id: classify
    name: Classify Changes
    agent: agents/classifier.md
    skill: skills/classify-diff.md
    input: $AGENT_INPUT
    goal: >
      Read the diff and classify the changes by type — features, bug fixes,
      refactors, tests, config, docs. Identify the scope and risk level.
    produces: outputs/01-classification.md

  - id: summarize
    name: Write PR Summary
    agent: agents/summarizer.md
    skill: skills/write-summary.md
    input: outputs/01-classification.md
    goal: >
      Write a clear PR summary that tells reviewers exactly what changed,
      what to focus on, and what the risk is.
    produces: outputs/02-summary.md
