name: dir-structure
version: 1.0.0
description: >
  prints the dir structure of the project

trigger:
  type: natural-language
  input_var: AGENT_INPUT

steps:
  - id: step-one
    name: First Step
    agent: agents/agent.md
    skill: skills/skill.md
    input: $AGENT_INPUT
    goal: >
      Describe what this step should achieve.
    produces: outputs/01-result.md
    gate: human-approval
